name: Generate GHA YAML from TeamCity DSL

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read DSL file content into a file
        id: read_dsl
        run: |
          cat teamcity-dsl-code/id10BuildPackage.kt > dsl_content.txt

      - name: Prepare Prompt
        id: prepare_prompt
        run: |
          echo "Preparing prompt with DSL content..."
          dsl_content=$(cat dsl_content.txt | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
          echo "PROMPT=Convert the following TeamCity Kotlin DSL build script into an equivalent GitHub Actions YAML workflow file. Ensure all steps are correctly migrated. Script: $dsl_content" >> $GITHUB_ENV

      - name: Generate GitHub Actions YAML via Azure OpenAI
        env:
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          PROMPT: ${{ env.PROMPT }}
        run: |
          echo "Calling Azure OpenAI..."
          
          body=$(jq -n \
            --arg content "$PROMPT" \
            '{
              "messages": [
                { "role": "system", "content": "You are a DevOps engineer." },
                { "role": "user", "content": $content }
              ],
              "temperature": 0.2,
              "max_tokens": 2000
            }')

          curl -s -X POST "$AZURE_OPENAI_ENDPOINT/openai/deployments/gpt-4/chat/completions?api-version=2023-12-01-preview" \
            -H "Content-Type: application/json" \
            -H "api-key: $AZURE_OPENAI_KEY" \
            -d "$body" > response.json

      - name: Extract and Save Generated YAML
        run: |
          cat response.json | jq -r '.choices[0].message.content' > generated-github-actions.yml

      - name: Upload Generated GHA YAML as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Generated-GHA-YAML
          path: generated-github-actions.yml
