name: Generate GHA YAML from TeamCity DSL

on:
  workflow_dispatch:   # Manual trigger

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read DSL file content
        id: read_dsl
        run: |
          echo "Reading DSL file..."
          dsl_content=$(cat teamcity-dsl-code/id10BuildPackage.kt | sed 's/"/\\"/g' | sed "s/'/\\'/g")
          echo "DSL_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$dsl_content" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Generate GitHub Actions YAML via Azure OpenAI
        env:
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
        run: |
          echo "Calling Azure OpenAI to generate GitHub Actions YAML..."

          body=$(jq -n --arg dsl "${{ env.DSL_CONTENT }}" '
          {
            "messages": [
              {"role": "system", "content": "You are a DevOps expert converting CI/CD scripts."},
              {"role": "user", "content": "Convert the following TeamCity Kotlin DSL build script into an equivalent GitHub Actions YAML workflow file. Script:\n---\n" + $dsl + "\n---\nEnsure all steps are correctly migrated."}
            ],
            "temperature": 0.2,
            "max_tokens": 2000
          }')

          curl -s -X POST "$AZURE_OPENAI_ENDPOINT/openai/deployments/gpt-4/chat/completions?api-version=2023-12-01-preview" \
            -H "Content-Type: application/json" \
            -H "api-key: $AZURE_OPENAI_KEY" \
            -d "$body" > response.json

      - name: Extract and Save Generated YAML
        run: |
          cat response.json | jq -r '.choices[0].message.content' > generated-github-actions.yml

      - name: Upload Generated GHA YAML as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Generated-GitHub-Action-YAML
          path: generated-github-actions.yml
